name: Deploy Next.js SSR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 코드
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. 원격 서버에서 배포 실행
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.REMOTE_PATH }}
          git checkout main
          git pull origin main

          # Docker Compose로 배포
          docker-compose down
          docker-compose up -d --build
          EOF
